# Generated by Django 2.2.13 on 2020-06-12 03:25

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Book',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=30)),
                ('author', models.CharField(max_length=100)),
                ('recommender', models.CharField(max_length=100)),
                ('source', models.TextField()),
                ('amazon_link', models.TextField()),
                ('description', models.TextField()),
                ('book_type', models.TextField()),
                ('genrer', models.TextField()),
                ('length', models.IntegerField()),
                ('publish_year', models.IntegerField()),
                ('on_list', models.TextField()),
                ('review_excerpt', models.TextField()),
            ],
        ),
    ]
