# Generated by Django 2.2.13 on 2020-06-13 22:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api_library', '0005_auto_20200613_0044'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='reviewer',
            name='book',
        ),
        migrations.AddField(
            model_name='reviewer',
            name='book',
            field=models.ManyToManyField(related_name='reviewers', to='api_library.Book'),
        ),
    ]
