# Generated by Django 2.2.13 on 2020-06-13 22:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api_library', '0006_auto_20200613_2201'),
    ]

    operations = [
        migrations.RenameField(
            model_name='reviewer',
            old_name='book',
            new_name='books',
        ),
    ]
