# Generated by Django 2.2.13 on 2020-06-14 02:21

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('api_library', '0007_auto_20200613_2239'),
    ]

    operations = [
        migrations.AddField(
            model_name='reviewer',
            name='user',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='books', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='reviewer',
            name='books',
            field=models.ManyToManyField(related_name='reviewers', related_query_name='reviewers', to='api_library.Book'),
        ),
    ]
