# Generated by Django 2.2.13 on 2020-06-14 03:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api_library', '0008_auto_20200614_0221'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='reviewer',
            name='name',
        ),
    ]
